### ISSUE TITLE
HTTP/2 Framing layer error

### ISSUE THREAD

**Issue by chrisdowsett** [ropensci/monkeylearn#14]
Hi 

I'm using a proxy with the monkey learn api. I can download the library OK. I can also see my classifier  when I use: monkeylearn_classifiers(private = FALSE, key = monkeylearn_key(quiet =                                                TRUE))

**But when I run through the examples I get hit with the following:** 

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Stream error in the HTTP/2 framing layer

when I look at curl_version() - the $http2 is listed as TRUE

Can you point me in the right direction for diagnosing the issue?

**Comment by jeroenooms** [comment]
This problem appears when the server has malconfigured http2 layer. I assume you're on windows?

**Comment by jeroenooms** [comment]
Can you try installing the development version of the curl package and see if this helps? You can't install curl with devtools because devtools uses curl. You need to restart to a clean empty R session and run:

```r
install.packages("https://github.com/jeroenooms/curl/archive/master.tar.gz", repos = NULL)
```

**Comment by chrisdowsett** [comment]
Thanks for the reply - yep on a windows machine. Ok, I think I'm getting closer. So I removed previous CURL package. Restarted RStudio & started the R session. 

Then I used the install code above and I got the following response which I've not seen before when installing a package:
`trying URL 'https://github.com/jeroenooms/curl/archive/master.tar.gz'
Content type 'application/x-gzip' length unknown
downloaded 75 KB

'\\int\Userdata\CustOpUser\U386475'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing *source* package 'curl' ...
Warning: running command 'sh ./configure.win' had status 127
ERROR: configuration failed for package 'curl'
* removing 'H:/1. R_Programs/R-Portable/App/R-Portable/library/curl'
Warning in install.packages :
  running command '"H:/1~1.R_P/R-PORT~1/App/R-PORT~1/bin/x64/R" CMD INSTALL -l "H:\1. R_Programs\R-Portable\App\R-Portable\library" "C:/Users/u386475/AppData/Local/Temp/Rtmp2vczbD/downloaded_packages/master.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/u386475/AppData/Local/Temp/Rtmp2vczbD/downloaded_packages/master.tar.gz’ had non-zero exit status`

**Comment by asjlyle** [comment]
I am on windows and experiencing the same issue, though everything was working fine last week so I'm not sure what has changed.

**Comment by masalmon** [comment]
@asjlyle and using @jeroenooms solution also fails?

**Comment by jeroenooms** [comment]
I released a new version of `curl` to cran, so hopefully windows builds are available later this week. Not sure if that will fix it, but I can't help you debug it without a reproducible example.

**Comment by masalmon** [comment]
Oops I realize *I* experience the bug too, bad practice to have packed my examples in don't run on Appveyor. I could install `curl` dev version but it didn't change anything.

@fecotryo nothing changed in the API for classifiy and extract in the last week?

**Comment by masalmon** [comment]
the `monkeylearn_classifiers` function works well but it's a `GET` not a `POST` call.

**Comment by masalmon** [comment]
Might be similar to https://github.com/r-hub/rhub/issues/32

**Comment by masalmon** [comment]
and similar to https://github.com/r-hub/rhub/issues/19

**Comment by masalmon** [comment]
@chrisdowsett and @asjlyle can you please install the development version of `monkeylearn`? The problem should have been fixed by @jeroenooms's PR.

**Comment by feconroses** [comment]
Hey @masalmon, we are taking a look at this issue! Most probably tomorrow we will circle back to you :)

**Comment by asjlyle** [comment]
@masalmon I have downloaded the package again and still no luck. Please let me know how to install the development version if you think this will help. Many Thanks

**Comment by masalmon** [comment]
Hi @asjlyle, do you have `devtools` installed? If you don't, you can get it with `install.packages("devtools") ` and then

```r
devtools::install_github("ropenscilabs/monkeylearn")
```
will install the development version of this package which has @jeroenooms awesome fix.

I haven't submitted the update to CRAN because @feconroses said Monkeylearn was looking at the issue on their side (which would make the CRAN version work again)

Thanks a lot for your patience!

**Comment by asjlyle** [comment]
@masalmon thanks for all your help. Unfortunately it's still not working for me and throwing an error about the memoise package. I'm not familiar with downloading and loading devtool packages so any pointers let me know.

> devtools::install_github("ropenscilabs/monkeylearn")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘memoise’
> devtools::install_github("hadley/memoise")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘memoise’

**Comment by masalmon** [comment]
@asjlyle sure, happy to help. Can you try `install.packages("memoise")` and then `devtools::install_github("ropenscilabs/monkeylearn")` ?

 Going to lunch now, will be back after that.

**Comment by asjlyle** [comment]
Thanks,

It returns the error below, so looks like it's my version of R which is the latest version.

install.packages("memoise")
Installing package into ‘C:/Users/user1/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘memoise’ is not available (for R version 3.3.2)

**Comment by masalmon** [comment]
Oh no it looks like dependencies hell right now. Can you give me your email address? Mine is maelle.salmon at yahoo.se I'll send you a .tar.gz of the development version, then in RStudio you'll be able to indicate where the .tar.gz is and the paclage will get installed.

**Comment by masalmon** [comment]
By the way it was a warning, not an error, so maybe the command `devtools::install_github("ropenscilabs/monkeylearn") ` would work now but please install with the .zip, it should be easier.

**Comment by chrisdowsett** [comment]
I just gave it a shot using the devtools but ran into an issue with "tibble" dependency not available for package. @masalmon I'll shoot you an email too for the tar.gz version too if that's ok. 
Here is my error message in case of interest:

```
> devtools::install_github("ropenscilabs/monkeylearn")
Using GitHub PAT from envvar GITHUB_PAT
Downloading GitHub repo ropenscilabs/monkeylearn@master
from URL https://api.github.com/repos/ropenscilabs/monkeylearn/zipball/master
Installing monkeylearn
Skipping 1 unavailable package: tibble
"C:/PROGRA~2/R/R-31~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/u386475/AppData/Local/Temp/Rtmp6Fep0f/devtools19f42ca94491/ropenscilabs-monkeylearn-1489b85"  \
  --library="C:/Program Files (x86)/R/R-3.1.1/library" --install-tests 

ERROR: dependency 'tibble' is not available for package 'monkeylearn'
* removing 'C:/Program Files (x86)/R/R-3.1.1/library/monkeylearn'
Error: Command failed (1)
```

**Comment by masalmon** [comment]
@chrisdowsett & @asjlyle do `monkeylearn_extract` and `monkeylearn_classify` now work for you? Thanks :-)

**Comment by gonz** [comment]
@masalmon http/2 support in API servers should be working now. Let me know if anything comes up.

**Comment by masalmon** [comment]
Thanks @gonz !

@jeroenooms Would you advise me to revert the modifications of https://github.com/ropensci/monkeylearn/pull/15/files ?

**Comment by masalmon** [comment]
@jeroenooms I'm unsure what is best, leaving the package as it is now i.e. not using http/2 although it is now supported by the API, or using http/2. What is your opinion on this?

**Comment by jeroenooms** [comment]
Best is to let the server/client automatically negotiate the protocol, i.e. revert the 'hack' which disables HTTP2.

**Comment by masalmon** [comment]
Ok thanks a lot!
