### ISSUE TITLE
New issue - works every second time approximately

### ISSUE THREAD

**Issue by maelle** [ropensci/monkeylearn#16]
From @asjlyle and I get it too. The example is 
```{r}
library("monkeylearn")
text <-  "Big Ben is a great monument in London. It has a wonderful view"
monkeylearn_extract(text,
                              extractor_id = "ex_y7BPYzNG")
```

What happens is:

![image](https://cloud.githubusercontent.com/assets/8360597/20640871/a2537a3a-b3eb-11e6-9693-bedf11c3c86e.png)

@feconroses is something up with the service today? @jeroenooms it doesn't look like a problem on `curl` side, right?

**Comment by masalmon** [comment]
@asjlyle so right now maybe make each call twice until it works... but that is clearly not a sustainable solution.

**Comment by gonz** [comment]
@masalmon @juliasilge We found a misconfiguration in our api loadbalancer, we have deployed a fix so everything should be working as usual now. Sorry for the inconvenience, we'll review the issue so this won't happen again. Thank you for the report, let me know if you need anything from our side.

**Comment by masalmon** [comment]
Thank you @gonz ! @asjlyle I hope I'll be ok now 😀

**Comment by asjlyle** [comment]
@masalmon @gonz the development version is working slightly better but still isn't usable, the live version on cran still throws the http2 error. Unfotunately  with the development one I'm getting a new error which is below. I'm only looping through 50 comments and it's been running for 10 minutes and still isn't finished. It's throwing the error below about half the time sporadically.

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

**Comment by masalmon** [comment]
@asjlyle let's see what @gonz says. Do you still use a try () in your loop? Maybe I need to add a Sys.sleep call in my code, In the meantime maybe you can add a Sys.sleep call in your loop?

**Comment by gonz** [comment]
@asjlyle @masalmon 

About the http2 error: **We currently recommend and support `http 1.1`, we do not support `http 2` officially**. `http 2` used to work fine but due to some load balancing related improvements we made recently it's not working reliably anymore. @masalmon we advice you to use `http 1.1` internally until we officially support `http 2`, we're working on this since you reported the issue (thank you!).

About the extraction error: @asjlyle I can see you are using our Keyword Extractor module. A Classifier or a pipeline module have sandbox and a live versions but this is not the case for extractors since you currently can't create custom extractors, so adding a `sandbox=1` query param doesn't make sense and will be ignored by MonkeyLearn.

(I just saw that in MonkeyLearn app UI the curl example on how to use a extractor (API/API libraries) has a `?sandbox=1` param that shouldn't be there, that just add to the adds up to the confusion, we'll fix that.)

@asjlyle I tried to reproduce the issue but the extractor is working fine using plain curl and our official libraries, My guess is that it might have something to do with your specific data or with the R library. Have you tried using curl (or similar) directly? Can you share your data with us? (You can contact us directly if you don't want to make you data public).

**Comment by masalmon** [comment]
@gonz thanks, @jeroenooms changed the package so that internally it no longer uses `http2`. (it used to use it because it was available)

**Comment by gonz** [comment]
@masalmon Yeah, that makes sense. I'll let you know when we have official support for it and it works again. Good thing is that when that happens, we'll will also setup our official libraries to use it and we'll make sure it keeps working from then on. Thanks again for your report, we really appreciate it!

**Comment by masalmon** [comment]
@asjlyle did the issue get solved on your side?

**Comment by masalmon** [comment]
@asjlyle do you still get this issue?

**Comment by maelle** [comment]
I'll consider this solved.
